# Generated by Django 3.0.3 on 2020-05-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='savedModel',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='result',
            name='date',
        ),
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AlterField(
            model_name='result',
            name='dataModel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='toolapp.DataModel'),
        ),
    ]
