# Generated by Django 3.0.3 on 2020-03-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.FileField(help_text='Файл с данными для загрузки, форматы: xlsx, csv.', upload_to='datasets/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(help_text='Описание набора данных', max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(help_text='Название набора данных', max_length=100, verbose_name='Название'),
        ),
    ]
