# Generated by Django 3.0.3 on 2020-03-02 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('toolapp', '0002_auto_20200303_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='data_format',
            field=models.CharField(choices=[('x', 'XLSX'), ('c', 'CSV')], default='x', max_length=5, verbose_name='Формат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
