# Generated by Django 3.0.3 on 2020-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolapp', '0003_auto_20200303_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
