# Generated by Django 3.0.3 on 2020-03-13 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolapp', '0006_auto_20200313_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='data',
        ),
        migrations.AddField(
            model_name='dataframe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
