# Generated by Django 3.0.3 on 2020-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolapp', '0007_auto_20200313_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='classColumn',
            field=models.TextField(default='', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='df',
            field=models.TextField(default='', verbose_name='DataFrame'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='featureColumns',
            field=models.TextField(default='', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='sampleColumn',
            field=models.TextField(default='', verbose_name='Sample'),
        ),
        migrations.DeleteModel(
            name='Dataframe',
        ),
    ]
